---
- name: install required packages
  pkgin: name="{{ item }}" state="present"
  ignore_errors: yes
  notify: enable powerdns-recursor
  with_items: "{{ net_powerdns_recursor_packages }}"
  tags:
          - recursor
          - install

- name: execute pre powerdns-recursor configuration tasks
  include: "{{ net_powerdns_recursor_pre_include }}"
  when: net_powerdns_recursor_pre_include is defined
  tags:
         - recursor
         - update


- name: copy powerdns-recursor configuration
  template: src="{{ net_powerdns_recursor_config_file_src }}" dest="{{ net_powerdns_recursor_config_file_dest }}" backup="yes" owner="{{ net_powerdns_recursor_username }}" group="{{ net_powerdns_recursor_groupname }}" mode="0644"
  notify: restart powerdns-recursor
  tags:
          - recursor
          - update

- name: get named.cache
  get_url: url="{{ net_powerdns_recursor_root_hints_url }}" dest="{{ net_powerdns_recursor_root_hints_file }}" owner="{{ net_powerdns_recursor_username }}" group="{{ net_powerdns_recursor_groupname }}" mode="0644"
  when: net_powerdns_recursor_root_hints_url is defined and net_powerdns_recursor_root_hints_file is defined
  tags:
          - recursor
          - update

- name: execute post powerdns-recursor configuration tasks
  include: "{{ net_powerdns_recursor_post_include }}"
  when: net_powerdns_recursor_post_include is defined
  tags:
         - recursor
         - update
